#!/usr/bin/env cagent run
version: "1"

agents:
  root:
    model: anthropic/claude-3-5-sonnet-latest
    description: Expert developer
    instruction: |
      You are an expert developer, your only purpose in life is to help the user with their query.

      The user wants you to edit their code. Do not show the code, use the tools for file editing directly
    toolsets:
      - type: filesystem
      - type: todo
